version: "3.8"

x-build: &dockerfile-dev-build
  context: .
  dockerfile: Dockerfile.dev

services:
  remote-interpreter:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
  tests:
    build: *dockerfile-dev-build
    working_dir: /app
    volumes:
      - .:/app
    command: [ "./scripts/start-tests.sh" ]
  lint:
    build: *dockerfile-dev-build
    working_dir: /app
    volumes:
      - .:/app
    command: [ "./scripts/start-lint.sh" ]
