version: "2.4"
services:
  remote-interpreter:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - .:/app
    command: ["./scripts/start-tests.sh"]
  lint:
      build:
        context: .
        dockerfile: Dockerfile.dev
      working_dir: /app
      volumes:
        - .:/app
      command: ["./scripts/start-lint.sh"]
