FROM python:3.9.2-buster

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    festival \
    festlex-cmu \
    festlex-poslex \
    espeak-ng && \
    apt-get clean

WORKDIR /app

COPY Pipfile Pipfile.lock ./

RUN pip install --no-cache-dir --upgrade pip pipenv

RUN pipenv install --system --deploy --dev --ignore-pipfile

RUN rm Pipfile Pipfile.lock
