name: Build and publish

on:
  push:
    branches:
      - main
    paths:
      - 'transcriber_wrapper/**'
      - 'setup.py'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel build
      - name: Building project
        run: python setup.py sdist bdist_wheel
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          skip_existing: true
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Execute tests
        run: docker-compose up --exit-code-from tests tests
      - name: Workaround to override source path
        run: >
          sed -i "s/<source>\/app\/transcriber_wrapper<\/source>/<source>\/github\/workspace\/transcriber_wrapper<\/source>/g" "$GITHUB_WORKSPACE/coverage.xml"
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # Needed to get PR information, if any
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.projectVersion=${{ github.sha }}
