name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'scripts/**'
      - 'sonar-project.properties'
      - '.github/workflows/tests.yml'
      - '.github/workflows/build-publish.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint evaluation
        run: docker-compose up --exit-code-from lint lint
