name: Tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'scripts/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute tests
        run: docker-compose up --exit-code-from tests tests
